FROM ubuntu:18.04
COPY . /root/reflex4arm

WORKDIR /root/reflex4arm

RUN apt-get update && apt-get install -y \
  libconfig-dev libnuma-dev libpciaccess-dev pciutils uuid-dev

RUN apt-get install -y \
  libconfig-dev libnuma-dev libpciaccess-dev libaio-dev libevent-dev g++-multilib

RUN apt-get install -y kmod

RUN ./usertools/conf_setup.sh
RUN ./usertools/precondition.sh
CMD ./usertools/run_reflex_server.sh